---
- hosts: all
  roles:
    - role: gantsign.visual-studio-code
      users:
      - username: vagrant
        visual_studio_code_settings: {
          "telemetry.enableCrashReporter": false,
          "telemetry.enableTelemetry": false
        }
